services:
  # Symfony backend
  backend:
    build: .
    container_name: backend
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_URL: "postgresql://app:verysecretpassword@database:5432/app"
    depends_on:
      - database
    networks:
      - backend_network  # Explicitly defining the network

  # PostgreSQL database
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: backend-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-verysecretpassword}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      retries: 5
      timeout: 5s
      start_period: 5s
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - backend_network  # Explicitly defining the network

  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  database_data:
    driver: local

networks:
  backend_network: 